ДЗ 1
DariaAkimov/2019-2-Track-Frontend-D-Akimova pull request #2
Opened 2019-10-05 22:29 UTC by DariaAkimov

# Домашнее задание 1
Прошу @martinkomitsky, @chexex или @priver проверить его.
Что было сделано:
*написаны три функции и один тест
*тестирование функций ( тесты прошли успешно)

2019-10-06 12:18 UTC, chexex requested changes
Подключить проект к travis-ci.org

После подключения выполнить любой коммит в проект, чтобы началась сборка.
После перезапросить ревью

2019-10-06 12:18 UTC, chexex commented on convertBytesToHuman.test.js
> +});
Добавить больше кейсов

2019-10-06 12:18 UTC, chexex commented on .travis.yml
> +  - cd web-components
Для первого дз не нужно (убрать эти строчки)

2019-10-06 12:18 UTC, chexex commented on .travis.yml
> +  local_dir: web-components/build
```suggestion
  local_dir: build
```

2019-10-07 20:27 UTC, chexex commented
Не вижу сборки, дай ссылку на свой сборщик, пожалуйста

2019-10-08 09:25 UTC, DariaAkimov commented
Ссылка на сборщик:
https://travis-ci.org/DariaAkimov/2019-2-Track-Frontend-D-Akimova

2019-10-09 18:16 UTC, chexex reviewed
Попрошу добавить больше тестовых кейсов для функции correctBytesToHuman.

2019-10-09 18:16 UTC, chexex commented on convertBytesToHuman.test.js
> +});
Объединить одинаковые типы тестов:
```js
test('Возвращает корректное значение для чисел', () => {
  expect(convertBytesToHuman(10)).toBe('10 b')
  expect(convertBytesToHuman(5)).toBe('5 b')
  // добавить БОЛЬШЕ кейсов: 1024, 1024 * 1024, 1024 * 1024 * 1024 * 2
})
```

2019-10-09 18:16 UTC, chexex commented on convertBytesToHuman.test.js
> +  // ...
строки комментариев не нужны :) они подразумевались как "здесь писать тест кейсы"

2019-10-09 18:16 UTC, chexex commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(-1)).toBe('false')
Больше тестов на неправильный тип данных:
```
undefined
null
Infinity
-Infinity
{}
[]
{some: 'non empty object'}
['a', 'r', 'r', 'a', 'y']
Symbol('symbol')
function(a) {return a}
new Date()
```

2019-10-10 15:47 UTC, chexex approved these changes
Не жалеть кейсов для тестов

Функции +
Тесты +
Сборка +

Спасибо за работу,
12 баллов

2019-10-10 15:47 UTC, merged